name: deploy to deploygate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: which one do you use?
        options:
          - A
          - B
          - C
      version_name:
        type: string
        required: true
        description: release version name
      version_code:
        type: string
        required: true
        description: release version code

env:
  ENVIRONMENT: ${{ inputs.environment }}

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.base_ref }}
     - name: set version_name and version_code
       uses: Devofure/advance-android-version-actions@v1.4
       with:
         gradlePath: app/build.gradle
         versionName: ${{ inputs.version_name }}
         versionCode: ${{ inputs.version_code }}
     - name: confirm version_name and version_code
       run: git diff     
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#          check-latest: true
#      - name: make gradlew executed
#        run: chmod +x ./gradlew
     - name: set keystore
       run: echo '${{ secrets.RELEASE_SECRET_KEY }}' | base64 -d > ./release.keystore
       env:
         TEST2: "bbbb"
     - name: check environment
       run: |
         echo "test $TEST" \
         echo "test2 $TEST2" \
         le -alh
       env:
         TEST: "aaaa"
#      - name: Build App Bundle
#        run: ./gradlew assembleRelease
#      - name: deploygate
#        run: |
#          curl \
#             -H "Authorization: token ${{secrets.DEPLOYGATE_API_TOKEN}}" \
#             -F "file=@app/build/outputs/apk/release/app-release-unsigned.apk" \
#             -F "message=test" \
#             -v "https://deploygate.com/api/users/${{ secrets.DEPLOYGATE_USER }}/apps"
#        env:
#          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
#          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
