name: deploy to deploygate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: which one do you use?
        options:
          - A
          - B
          - C
      version:
        type: string
        required: true
        description: release version

env:
  ENVIRONMENT: ${{ inputs.environment }}
  VERSION: ${{ inputs.version }}

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.base_ref }}
     - name: set up JDK 11
       uses: actions/setup-java@v2
       with:
         distribution: 'temurin'
         java-version: '11'
         check-latest: true
     - name: Build App Bundle
       run: ./gradlew assembleRelease
     - name: Found App
       run: ls app/build/outputs/apk/release/app-release-unsigned.apk
     - name: deploygate
       run: |
         curl \
            -H "Authorization: token ${{secrets.DEPLOYGATE_API_TOKEN}}" \
            -F "file=@app/build/outputs/apk/release/app-release-unsigned.apk" \
            -F "message=test" \
            -v "https://deploygate.com/api/users/odzbdadd100/apps"
