name: deploy to deploygate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: which one do you use?
        options:
          - A
          - B
          - C
      version_name:
        type: string
        required: true
        description: release version name
      version_code:
        type: int
        required: true
        description: release version code

env:
  ENVIRONMENT: ${{ inputs.environment }}
  VERSION: ${{ inputs.version }}

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.base_ref }}
     - name: set version_name and version_code
       run: sed -i"" -e "/versionName/s/[0-9]*\.[0-9]*/${{ inputs.version_name }}/"　 ./app/build.gradle
#        run: |
#          sed -i "" -e "/versionName/s/[0-9]*\.[0-9]*/${{ inputs.version_name }}/" app/build.gradle \
#          sed -i "" -e "/versionCode/s/[0-9]\{1,\}/${{ inputs.version_code }}/" app/build.gradle
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#          check-latest: true
#      - name: make gradlew executed
#        run: chmod +x ./gradlew
#      - name: Build App Bundle
#        run: ./gradlew assembleRelease
#      - name: deploygate
#        run: |
#          curl \
#             -H "Authorization: token ${{secrets.DEPLOYGATE_API_TOKEN}}" \
#             -F "file=@app/build/outputs/apk/release/app-release-unsigned.apk" \
#             -F "message=test" \
#             -v "https://deploygate.com/api/users/${{ secrets.DEPLOYGATE_USER }}/apps"
