name: deploy to deploygate

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: which one do you use?
        options:
          - A
          - B
          - C
      version:
        type: string
        required: true
        description: release version

env:
  ENVIRONMENT: ${{ inputs.environment }}
  VERSION: ${{ inputs.version }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
     - uses: actions/checkout@v1
     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
         
       
