name: release
run-name: release ${{ inputs.version_name }} (${{ inputs.version_code }} )

on:
  workflow_dispatch:
    inputs:
      version_name:
        type: string
        required: true
        description: release version name
      version_code:
        type: number
        required: true
        description: release version code

env:
  ENVIRONMENT: 'Release'
#   VERSION_NAME: ${{ inputs.version_name }}
#   VERSION_CODE: ${{ inputs.version_code }}
#   RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
#   RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
#   RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - name: test
         run: echo ${{ env.ENVIRONMENT }}
       - name: change env
         run: ENVIRONMENT="degub" >> $GITHUB_ENV
       - name: test env
         run: echo ${{ env.ENVIRONMENT }}
#      - uses: actions/checkout@v1
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v3
#      - name: confirm version_name and version_code
#        run: |
#          git diff
#          echo $REF
#          echo $ENV
#        env:
#          ENV: "Release"
#          REF: ${{ github.base_ref }}
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#          check-latest: true
#      - name: make gradlew executed
#        run: chmod +x ./gradlew
#      - name: set keystore
#        run: echo '${{ secrets.RELEASE_SECRET_KEY }}' | base64 -d > ./release.keystore
#      - name: Build aab
#        run: |
#          ./gradlew bundle$ENV \
#          -Pandroid.injected.signing.store.file='./release.keystore' \
#          -Pandroid.injected.signing.store.password=$RELEASE_STORE_PASSWORD \
#          -Pandroid.injected.signing.key.alias=$RELEASE_KEY_ALIAS \
#          -Pandroid.injected.signing.key.password=$RELEASE_KEY_PASSWORD
#        env:
#          ENV: ${{ env.ENVIRONMENT }}
#          RELEASE_STORE_PASSWORD: ${{ env.RELEASE_STORE_PASSWORD }}
#          RELEASE_KEY_ALIAS: ${{ env.RELEASE_KEY_ALIAS }}
#          RELEASE_KEY_PASSWORD: ${{ env.RELEASE_KEY_PASSWORD }}
#      - name: Release
#        uses: r0adkll/upload-google-play@v1
#        with:
#          releaseFiles: ${{ secrets.SERVICE_ACCOUNT_JSON }}
#          serviceAccountJsonPlainText: ./service-account.json
#          packageName: com.example.sampleandroid
#          track: bate
#   notice:
#     runs-on: ubuntu-latest
#     needs: 
#       - deploy
#     steps:
#       - name: Send GitHub Action trigger data to Slack workflow
#         id: slack
#         uses: slackapi/slack-github-action@v1.23.0
#         with:
#           payload: |
#             {
#               "text": "github actions: status ${{ job.status}} : environment: ${{ env.ENVIRONMENT }}, versions: ${{ env.VERSION_NAME }} (${{ inputs.version_code }})"
#             }
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
